added storage config and splitted functional and visual tests

diff --git a/.github/workflows/parallel.yml b/.github/workflows/parallel.yml
--- a/.github/workflows/parallel.yml
+++ b/.github/workflows/parallel.yml
@@ -1,3 +1,64 @@
+# name: test-automation
+
+# on:
+#   workflow_dispatch:
+#     inputs:
+#       website:
+#         type: choice
+#         options: [ACPH, ICPH]
+#         required: true
+#       testing-type:
+#         type: choice
+#         options: [Functional, Visual]
+#         required: true
+#       browser-type:
+#         type: choice
+#         description: "Not required for Visual Testing"
+#         options: [chrome, firefox, edge]
+#         required: true
+#       env-type:
+#         type: choice
+#         description: "Not required for Visual Testing"
+#         options: [prod, stage, dev]
+#         required: true
+
+# jobs:
+#   set-params:
+#     runs-on: ubuntu-latest
+#     outputs:
+#       command: ${{ steps.set-command.outputs.command }}
+#       spec: ${{ steps.set-command.outputs.spec }}
+#     steps:
+#       - id: set-command
+#         run: |
+#           if [[ "${{ github.event.inputs.testing-type }}" == "Visual" ]]; then
+#             if [[ "${{ github.event.inputs.website }}" == "ACPH" ]]; then
+#               echo "command=npx percy exec -- cypress run --spec cypress/e2e/Visual/acph_percy.cy.js --env environment=${{ github.event.inputs.env-type }} --config-file cypress.acph.config.js" >> "$GITHUB_OUTPUT"
+#             else
+#               echo "command=npx percy exec -- cypress run --spec cypress/e2e/Visual/icph_percy.cy.js --env environment=${{ github.event.inputs.env-type }} --config-file cypress.icph.config.js" >> "$GITHUB_OUTPUT"
+#             fi
+#             echo "spec=" >> "$GITHUB_OUTPUT"
+#           else
+#             config_file=$([[ "${{ github.event.inputs.website }}" == "ACPH" ]] && echo "cypress.acph.config.js" || echo "cypress.icph.config.js")
+#             echo "command=npx cypress run --env environment=${{ github.event.inputs.env-type }} --browser ${{ github.event.inputs.browser-type }} --config-file $config_file" >> "$GITHUB_OUTPUT"
+#             echo "spec=cypress/e2e/Functional/${{ github.event.inputs.website }}/*.cy.js" >> "$GITHUB_OUTPUT"
+#           fi
+
+#   split:
+#     needs: set-params
+#     uses: ./.github/workflows/reusable.yml
+#     with:
+#       n: ${{ github.event.inputs['testing-type'] == 'Visual' && 1 || 23 }}
+#       working-directory: "test-automation"
+#       marge: true
+#       command: ${{ needs.set-params.outputs.command }}
+#       spec: ${{ needs.set-params.outputs.spec }}
+#     secrets:
+#       CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
+#       CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
+#       PERCY_TOKEN: ${{ secrets[github.event.inputs.website == 'ACPH' && 'ACPH_PERCY_TOKEN' || 'ICPH_PERCY_TOKEN'] }}
+
+
 name: test-automation
 
 on:
@@ -23,37 +84,62 @@ on:
         required: true
 
 jobs:
-  set-params:
+
+  visual-tests:
+    if: ${{ github.event.inputs.testing-type == 'Visual' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v3
+
+      - name: Set Percy token
+        run: |
+          if [ "${{ github.event.inputs.website }}" = "ACPH" ]; then
+            echo "Using ACPH Percy token"
+            echo "PERCY_TOKEN=${{ secrets.ACPH_PERCY_TOKEN }}" >> $GITHUB_ENV
+          elif [ "${{ github.event.inputs.website }}" = "ICPH" ]; then
+            echo "Using ICPH Percy token"
+            echo "PERCY_TOKEN=${{ secrets.ICPH_PERCY_TOKEN }}" >> $GITHUB_ENV
+          else
+            echo "❌ Invalid website selection"
+            exit 1
+          fi
+
+      - name: Run Visual Tests with Percy
+        env:
+          PERCY_TOKEN: ${{ env.PERCY_TOKEN }}
+        run: |
+          if [ "${{ github.event.inputs.website }}" = "ACPH" ]; then
+            npx percy exec -- cypress run --spec cypress/e2e/Visual/acph_percy.cy.js --env environment=${{ github.event.inputs.env-type }} --config-file cypress.acph.config.js
+          else
+            npx percy exec -- cypress run --spec cypress/e2e/Visual/icph_percy.cy.js --env environment=${{ github.event.inputs.env-type }} --config-file cypress.icph.config.js
+          fi
+        working-directory: test-automation
+
+  functional-tests:
+    if: ${{ github.event.inputs.testing-type == 'Functional' }}
     runs-on: ubuntu-latest
     outputs:
       command: ${{ steps.set-command.outputs.command }}
       spec: ${{ steps.set-command.outputs.spec }}
     steps:
-      - id: set-command
+      - name: Set command and spec
+        id: set-command
         run: |
-          if [[ "${{ github.event.inputs.testing-type }}" == "Visual" ]]; then
-            if [[ "${{ github.event.inputs.website }}" == "ACPH" ]]; then
-              echo "command=npx percy exec -- cypress run --spec cypress/e2e/Visual/acph_percy.cy.js --env environment=${{ github.event.inputs.env-type }} --config-file cypress.acph.config.js" >> "$GITHUB_OUTPUT"
-            else
-              echo "command=npx percy exec -- cypress run --spec cypress/e2e/Visual/icph_percy.cy.js --env environment=${{ github.event.inputs.env-type }} --config-file cypress.icph.config.js" >> "$GITHUB_OUTPUT"
-            fi
-            echo "spec=" >> "$GITHUB_OUTPUT"
-          else
-            config_file=$([[ "${{ github.event.inputs.website }}" == "ACPH" ]] && echo "cypress.acph.config.js" || echo "cypress.icph.config.js")
-            echo "command=npx cypress run --env environment=${{ github.event.inputs.env-type }} --browser ${{ github.event.inputs.browser-type }} --config-file $config_file" >> "$GITHUB_OUTPUT"
-            echo "spec=cypress/e2e/Functional/${{ github.event.inputs.website }}/*.cy.js" >> "$GITHUB_OUTPUT"
-          fi
+          config_file=$([[ "${{ github.event.inputs.website }}" == "ACPH" ]] && echo "cypress.acph.config.js" || echo "cypress.icph.config.js")
+          echo "command=CYPRESS_NO_COMMAND_LOG=1 npx cypress run --no-runner-ui --env environment=${{ github.event.inputs.env-type }} --browser ${{ github.event.inputs.browser-type }} --config-file $config_file" >> $GITHUB_OUTPUT
+          echo "spec=cypress/e2e/Functional/${{ github.event.inputs.website }}/*.cy.js" >> $GITHUB_OUTPUT
 
   split:
-    needs: set-params
+    if: ${{ github.event.inputs.testing-type == 'Functional' }}
+    needs: functional-tests
     uses: ./.github/workflows/reusable.yml
     with:
-      n: ${{ github.event.inputs['testing-type'] == 'Visual' && 1 || 23 }}
+      n: 23
       working-directory: "test-automation"
       marge: true
-      command: ${{ needs.set-params.outputs.command }}
-      spec: ${{ needs.set-params.outputs.spec }}
+      command: ${{ needs.functional-tests.outputs.command }}
+      spec: ${{ needs.functional-tests.outputs.spec }}
     secrets:
       CYPRESS_username: ${{ secrets.CYPRESS_USERNAME }}
       CYPRESS_password: ${{ secrets.CYPRESS_PASSWORD }}
-      PERCY_TOKEN: ${{ secrets[github.event.inputs.website == 'ACPH' && 'ACPH_PERCY_TOKEN' || 'ICPH_PERCY_TOKEN'] }}
